name: part_tracker
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.6.2+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  get: ^4.7.3
  flutter_fancy_tree_view: ^1.6.0
  intl: ^0.20.2
  sembast: ^3.8.6
  path_provider: ^2.1.5
  data_on_image_view:
    git:
      url: https://github.com/lavruh/data_on_image_view.git
  file_provider:
    git: https://github.com/lavruh/file_provider.git

  archive: ^4.0.7
  shared_preferences: ^2.5.4
  package_info_plus: ^9.0.0
  window_manager: ^0.5.1
  permission_handler: ^12.0.1
  restart_app:
    git: https://github.com/lavruh/restart_app.git
  markdown_widget: ^2.3.2+8
  device_info_plus: ^12.3.0
  popover: ^0.4.0
  open_file: ^3.5.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  analyzer: ^7.4.5
  mockito: ^5.4.6

flutter:
  uses-material-design: true
  assets:
   - assets/overview.png
   - assets/help/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
